services:
  app:
    container_name: forum-app
    image: forum-app:prod
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      NITRO_HOST: "0.0.0.0"
      NITRO_PORT: ${PORT:-3000}
    restart: unless-stopped
    networks:
      - forum.test

networks:
  forum.test:
    name: forum.test
    external: true
