export const iconList = {
  lightbulb: 'material-symbols:lightbulb-2-outline-rounded',
  accountBalance: 'material-symbols:account-balance-outline',
  rightArrow: 'material-symbols:arrow-right-alt-rounded',
  leftArrow: 'material-symbols:arrow-left-alt-rounded',
  checkMark: 'material-symbols:check-rounded',
  money: 'material-symbols:money-range-outline-rounded',
  partner: 'material-symbols:partner-exchange',
  feedback: 'material-symbols:feedback-outline-rounded',
  network: 'material-symbols:network-node',
  search: 'material-symbols:search',
  chart: 'material-symbols:chart-data-outline',
  peers: 'material-symbols:p2p-outline-sharp',
  barChart: 'material-symbols:bar-chart-4-bars-rounded',
  camera: 'material-symbols:photo-camera-outline-rounded',
  check: 'material-symbols:fitbit-check-small-rounded',
  home: 'material-symbols:home-outline',
  message: 'material-symbols:chat-bubble-outline-rounded',
  notification: 'material-symbols:notifications-outline-rounded',
  chevron: 'material-symbols:keyboard-arrow-down-rounded',
} as const
